### ISSUE TITLE
Configure shouldn't be doing installs

### ISSUE THREAD

**Issue by hardaker** [cisco/mercury#1]
If you just run `./configure` as a regular user it fails because:

```
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib64/python3.7'
Consider using the `--user` option or check the permissions.
```

In general, configure scripts should actually modify the system or other envornments.  Maybe move that to make?

**Comment by davidmcgrew** [comment]
Hi Wes,

We are still working out packaging and a few other issues; we will announce the package once it’s sorted through.  Thanks for reporting the issue, which I am sure you have figured out is due to your pip3/python3 configuration.

David

**Comment by hardaker** [comment]
Gotcha :-)
