### ISSUE TITLE
[Patch] Support for overriding default compilers

### ISSUE THREAD

**Issue by layertwo** [cisco/mercury#21]
## Summary

I have been working on building Mercury for Amazon Linux 2 (AL2). AL2 _has_ GCC, but is an older version that doesn't support C++17 standards. This requires me to install GCC10 instead:

```
yum install gcc10 gcc10-c++
```

The problem that emerges is that GCC10 for AL2 (and likely other RHEL based distros) doesn't install GCC10 as `/usr/bin/gcc`, but rather `/usr/bin/gcc10-gcc` (also applies to `g++`) as well.

The solution for this is to override `CC`, `CPP`, and `CXX` during `make`, however there are a handful of places in checked in Makefiles which assumes uses `g++` directly rather than the `CXX` variable.

```
make CC=/usr/bin/gcc10-gcc CPP=/usr/bin/gcc10-cpp CXX=/usr/bin/gcc10-c++ V=s
```

## Solution

I have include the patch for updating Makefiles to use the build time compiler and not static paths. Also uploaded [here](https://github.com/cisco/mercury/files/8344703/01_cxx_override.txt).

```
diff --git a/src/Makefile.in b/src/Makefile.in
index 85c1bb2..9154890 100644
--- a/src/Makefile.in
+++ b/src/Makefile.in
@@ -225,7 +225,7 @@ libmerc_driver:
 #
 
 intercept.so: intercept.cc libmerc.a
-	g++ -std=c++17 -Wall -Wno-narrowing intercept.cc libmerc/pkt_proc.cc -D_GNU_SOURCE -I/usr/include/nspr/ -fPIC -shared -lssl -lnspr4 -lgnutls libmerc/libmerc.a -o intercept.so
+	$(CXX) -std=c++17 -Wall -Wno-narrowing intercept.cc libmerc/pkt_proc.cc -D_GNU_SOURCE -I/usr/include/nspr/ -fPIC -shared -lssl -lnspr4 -lgnutls libmerc/libmerc.a -o intercept.so
 
 # special targets
 #
diff --git a/src/libmerc/lctrie/Makefile b/src/libmerc/lctrie/Makefile
index bbc45e7..5bc2b5a 100644
--- a/src/libmerc/lctrie/Makefile
+++ b/src/libmerc/lctrie/Makefile
@@ -12,7 +12,6 @@ clean:
 	rm -f lctrie_test
 	rm -f liblctrie.a
 
-CC     = g++
 CFLAGS = -g -ggdb -std=c++11 -Wall -O3 -fPIC # -Wno-sign-compare
 LDFLAGS = -g -ggdb -O3
 LDLIBS =
@@ -23,7 +22,7 @@ DEPDIR := .d
 $(shell mkdir -p $(DEPDIR) >/dev/null)
 DEPFLAGS = -MT $@ -MMD -MP -MF $(DEPDIR)/$*.Td
 
-COMPILE.c = $(CC) $(DEPFLAGS) $(CFLAGS) $(CPPFLAGS) $(TARGET_ARCH) -c
+COMPILE.c = $(CXX) $(DEPFLAGS) $(CFLAGS) $(CPPFLAGS) $(TARGET_ARCH) -c
 COMPILE.cc = $(CXX) $(DEPFLAGS) $(CXXFLAGS) $(CPPFLAGS) $(TARGET_ARCH) -c
 POSTCOMPILE = mv -f $(DEPDIR)/$*.Td $(DEPDIR)/$*.d
 
```

Please let me know if you have any questions.

**Comment by davidmcgrew** [comment]
Thanks layertwo for reporting the problem and providing a fix.  We applied the changes and they will show up in the next update.   Please let us know if there are any more issues.
