### ISSUE TITLE
Unable to install latest pypi versions of pmercury on ARM platforms

### ISSUE THREAD

**Issue by cglewis** [cisco/mercury#4]
Looks like the way the latest versions were uploaded to pypi don't make it compatible with other platforms like it did it earlier versions:
```
#21 [linux/arm64 5/5] RUN pip3 install --no-cache-dir -r requirements.txt
#21 11.99 ERROR: Could not find a version that satisfies the requirement pmercury==0.4.3.16 (from -r requirements.txt (line 2)) (from versions: 0.1.0.0, 0.1.1.0, 0.1.3.1, 0.2.0.1, 0.2.1.2, 0.2.1.3)
```
It would useful to be able to install this on ARM like it used to be.

**Comment by banderson84** [comment]
Sorry for the delay, we were performing a lot of internal branch management. I transitioned pmercury back to a pure python implementation, which should help portability. Let me know if the most recent version (0.5.x) is still having these problems.

**Comment by cglewis** [comment]
@banderson84 confirmed as working now. thank you!
