### ISSUE TITLE
adduser not available for some distro

### ISSUE THREAD

**Issue by Lynxiayel** [cisco/mercury#5]
the makefile uses `adduser --system --no-create-home --group mercury` to add a new user `mercury` and create a same-named group.

`adduser` is an actual alias for `useradd ` and may not be available in some linux distros (eg. OpenSUSE). This will cause `make install` to fail.

The equivalent command should be `useradd --system --user-group mercury` in these distros.

**Comment by davidmcgrew** [comment]
Thanks for reporting this.  It looks like useradd is present on Debian/Ubuntu and CentOS, so I will go ahead and switch from adduser, once I have tested the change.

**Comment by davidmcgrew** [comment]
src/Makefile.in and the .deb/.rpm package builder both switched over to useradd.
